### ISSUE TITLE
Ça marche pas !

### ISSUE THREAD

**Issue by DACC4** [QuicksandStudio/anywhere-android#1]
Je n'arrive pas à avoir autre chose que un "Hello World" affiché, des idées ?

NAN MAIS C'EST PARCE-QUE JE SUIS TRES TRES CON

**Comment by Ministoud** [comment]
Ben c normal konar on a pa enkor kodé

**Comment by DACC4** [comment]
> Ben c normal konar on a pa enkor kodé

PAS SYMPA

**Comment by DACC4** [comment]
CA MARCHE TOUJOURS PAS

**Comment by Ministoud** [comment]
BEN NIQUE

**Comment by DACC4** [comment]
JE SUIS TOUT PUISSANT
